---
name: Manual setup of release-please
description: Installs release please and all required dependencies.
runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
      with:
        node-version: "24"

    - name: Install release-please CLI
      run: npm install -g release-please@17.4.0
      shell: bash
