---
name: Actionlint
on:
  pull_request:
    branches: ["main"]
  workflow_call:
    inputs:
      runner:
        description: GitHub Actions runner to use. Supports a single label or a JSON array of labels.
        required: false
        type: string
        default: ubuntu-24.04

permissions: {}

concurrency:
  group: actionlint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint workflows and local actions
    runs-on: ${{ startsWith(inputs.runner, '[') && fromJSON(inputs.runner) || (inputs.runner != '' && inputs.runner || (vars.DEFAULT_ORG_RUNNER || 'ubuntu-24.04')) }}
    permissions:
      contents: read
      checks: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Run actionlint with reviewdog
        uses: reviewdog/action-actionlint@dbe5299849118fd6f099ba563d263d770955a64a # v1.73.2
        with:
          reporter: github-pr-check
          fail_level: any
          filter_mode: nofilter
          actionlint_flags: "-config-file .github/actionlint.yaml"

      - name: Ensure Node.js is available
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: "24"

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: 3.x

      - name: Install pipx
        run: |
          python3 -m pip install pipx
          python3 -m pipx ensurepath

      - name: Run actionlint on workflows
        uses: raven-actions/actionlint@3d39aea434753780c3b3d4a1a31c854b4dbf49d7 # v2
        with:
          version: 1.7.12
          matcher: true

      - name: Validate local actions
        if: ${{ always() }}
        uses: naviteq/github-actions/.github/actions/action-lint@e7630149683fc543b988a362b18bed7b2d12585e
        with:
          actions: .github/actions/*/action.y*ml
