---

name: Create GitHub release
on:
  push:
    branches: [main]
  workflow_call:
    secrets:
      PROJECT_GITHUB_TOKEN:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      changelog: ${{ steps.tag_version.outputs.changelog }}
    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.PROJECT_GITHUB_TOKEN }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
  notify:
    needs: [release]
    runs-on: ubuntu-latest
    steps:
      - uses: slackapi/slack-github-action@v1.22.0
        if: env.SLACK_WEBHOOK_URL != null
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_GITHUB_INTEGRATION_WEBHOOK }}
        with:
          slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}\nChangelog: ${{ needs.release.outputs.changelog }}"
