---
name: Create GitHub release
on:
  workflow_call:
    inputs:
      RUNNER:
        description: GitHub Actions runner to use. Supports a single label or a JSON array of labels.
        type: string
        required: false
        default: ubuntu-24.04
    secrets:
      GITHUB_APP_ID:
        required: true
      GITHUB_APP_KEY:
        required: true

jobs:
  release:
    runs-on: ${{ startsWith(inputs.RUNNER, '[') && fromJSON(inputs.RUNNER) || inputs.RUNNER }}
    steps:
      - name: Generate GitHub App token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.GITHUB_APP_ID }}
          private-key: ${{ secrets.GITHUB_APP_KEY }}
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@d745f2e74aaf1ee82e747b181f7a0967978abee0
        with:
          github_token: ${{ steps.app-token.outputs.token }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@d82d180c1d8147d23544f9d2610bf8a1941af66e
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          token: ${{ steps.app-token.outputs.token }}
