---

name: Docker build
on:
  workflow_call:
    inputs:
      DOCKER_CONTEXT:
        description: Docker build context
        type: string
        default: '.'
      DOCKER_PUSH:
        description: Do we should push the image or not
        type: boolean
        default: true
      REGISTRY:
        description: Registry URL
        type: string
        default: ''
      USERNAME:
        description: Registry Username
        type: string
        default: ''
      IMAGE:
        description: Image name
        type: string
      AWS_REGION:
        description: AWS Region
        type: string
        required: false
    secrets:
      TOKEN:
        description: Registry Token
        required: false
      AWS_IAM_ROLE:
        description: AWS IAM Role to assume 
        required: false

jobs:
  build:
    name: Docker build and push to registry
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # Auth
      ## AWS
      - uses: aws-actions/configure-aws-credentials@v4
        if: inputs.AWS_REGION != ''
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          role-session-name: github-${{ github.repository_id }}-${{ github.triggering_actor }}
          aws-region: ${{ inputs.AWS_REGION }}
      - name: Login to Amazon ECR
        if: inputs.AWS_REGION != ''
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2
      ## Other
      - name: Login to registry (using username and token)
        if: inputs.USERNAME != ''
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.REGISTRY }}
          username: ${{ inputs.USERNAME }}
          password: ${{ secrets.TOKEN }}
      - name: Prepare Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.AWS_REGION != '' && steps.ecr.outputs.registry || inputs.REGISTRY }}/${{ inputs.IMAGE }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=semver,pattern={{major}}.{{minor}}
            type=sha
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.DOCKER_CONTEXT }}
          push: ${{ inputs.DOCKER_PUSH }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            ${{ inputs.REGISTRY }}/${{ inputs.IMAGE }}:latest
            type=gha,scope=${{ github.ref_name }}-${{ inputs.IMAGE }}
          cache-to: type=gha,mode=max,scope=${{ github.ref_name }}-${{ inputs.IMAGE }}
