---

name: Docker build
on:
  workflow_call:
    inputs:
      REGISTRY:
        type: string
      IMAGE:
        type: string
      USERNAME:
        type: string
    secrets:
      TOKEN:
        required: true

jobs:
  build:
    name: Docker build and push to registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.REGISTRY }}
          username: ${{ inputs.USERNAME }}
          password: ${{ secrets.TOKEN }}
      - name: Prepare Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ inputs.REGISTRY }}/${{ inputs.IMAGE }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=semver,pattern={{major}}.{{minor}}
            type=sha
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            ${{ steps.ecr.outputs.registry }}/${{ inputs.IMAGE }}:latest
            type=gha,scope=${{ github.ref_name }}-${{ inputs.IMAGE }}
          cache-to: type=gha,mode=max,scope=${{ github.ref_name }}-${{ inputs.IMAGE }}
