---

name: Docker build TEST
on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  case_local_build_success:
    name: Case - local build succeeds
    uses: ./.github/workflows/docker-build.yaml
    with:
      RUNNER: ubuntu-latest
      REGISTRY: ghcr.io
      USERNAME: ${{ github.actor }}
      IMAGE: ${{ github.repository }}
      DOCKER_CONTEXT: '.'
      DOCKER_PLATFORMS: linux/amd64,linux/arm64
      DOCKERFILE: fixtures/docker-build/Dockerfile.green
      BUILD_ARGS: |
        TEST_ARG=enabled
        TEST_ARG_2=enabled
      TAG_FLAVOR_PREFIX: 'prefix-'
      TAG_FLAVOR_SUFFIX: '-suffix'
      VERSION_TAG_V_PREFIX: true
      CUSTOM_TAGS: |
        test-custom-tag
      DOCKER_PUSH: false
      SECURITY_SCAN_ENABLED: true
      SECURITY_SCAN_SEVERITY: CRITICAL
      SECURITY_SCAN_EXIT_CODE: '0'
      SBOM_ENABLED: true
      SLACK_NOTIFY_ON_SUCCESS: false
