---

name: Helm release
on:
  workflow_call:
    inputs:
      CHART_LOCATION:
        type: string
      UPDATE_BRANCH:
        type: string
      ENVIRONMENT:
        type: string

jobs:
  helm:
    name: Update Chart.yaml file for version\appVersion and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Lint Helm chart
        working-directory: ${{ inputs.CHART_LOCATION }}
        env:
          ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
        run: |
          if [[ -n "$ENVIRONMENT" ]]
          then
            helm lint -f values/$ENVIRONMENT.yaml
          else
            helm lint .
          fi

      - name: Update versions
        if: ${{ github.ref_type == 'tag' }}
        working-directory: ${{ inputs.CHART_LOCATION }}
        env:
          ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
        run: |
          APP_VERSION="${GITHUB_REF_NAME##*/}"
          echo "Updating Chart.yaml"
          sed -i "s#^version:.*#version: ${APP_VERSION/v/}#g" Chart.yaml
          sed -i "s#^appVersion:.*#appVersion: ${APP_VERSION}#g" Chart.yaml
          cat Chart.yaml

      - name: Commit file to branch
        if: ${{ github.ref_type == 'tag' }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Bumped up version and appVersion [skip ci]"
          branch: ${{ inputs.UPDATE_BRANCH }}
          commit_user_name: Naviteq Automation
          commit_user_email: naviteq-automation@naviteq.io

      - name: Build Helm chart
        working-directory: ${{ inputs.CHART_LOCATION }}
        run: helm package .
      # TODO: Add optional push step
