---

name: Helm release
on:
  workflow_call:
    inputs:
      CHART_LOCATION:
        type: string
      UPDATE_BRANCH:
        type: string
      ENVIRONMENT:
        type: string
      PUSH_TO_GITHUB:
        type: boolean
        default: false
    secrets:
      TOKEN:
        required: true

jobs:
  helm:
    name: Update Chart.yaml file for version\appVersion and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # needed for tags
          ref: ${{ github.head_ref }}
          token: ${{ secrets.TOKEN }}
      - uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Lint Helm chart
        working-directory: ${{ inputs.CHART_LOCATION }}
        env:
          ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
        run: |
          if [[ -n "$ENVIRONMENT" ]]
          then
            helm lint -f values/$ENVIRONMENT.yaml
          else
            helm lint .
          fi

      - name: Update versions
        working-directory: ${{ inputs.CHART_LOCATION }}
        run: |
          if [[ "$GITHUB_REF_TYPE" == "branch" ]]
          then
            LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
            APP_VERSION="$LATEST_TAG-pre+$(echo ${GITHUB_SHA} | cut -c1-7)" 
          else
            APP_VERSION="${GITHUB_REF_NAME##*/}"
          fi
          echo "Updating Chart.yaml"
          sed -i "s#^version:.*#version: ${APP_VERSION/v/}#g" Chart.yaml
          sed -i "s#^appVersion:.*#appVersion: ${APP_VERSION}#g" Chart.yaml
          cat Chart.yaml

      - name: Build Helm chart
        working-directory: ${{ inputs.CHART_LOCATION }}
        run: helm package .

      - name: Commit file to branch
        if: ${{ github.ref_type == 'tag' }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Bumped up version and appVersion [skip ci]"
          branch: ${{ inputs.UPDATE_BRANCH }}
          commit_user_name: Naviteq Automation
          commit_user_email: naviteq-automation@naviteq.io

      - name: Checkout Helm repo museum
        if: ${{ github.ref_type == 'tag' && inputs.PUSH_TO_GITHUB }}
        uses: actions/checkout@v3
        with:
          repository: naviteq/helm-charts
          path: helm-charts
          token: ${{ secrets.TOKEN }}
      - name: Copy Helm chart to museum
        if: ${{ github.ref_type == 'tag' && inputs.PUSH_TO_GITHUB }}
        run: cp ${{ inputs.CHART_LOCATION }}/*.tgz helm-charts
      - name: Publish Helm charts
        if: ${{ github.ref_type == 'tag' && inputs.PUSH_TO_GITHUB }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: helm-charts
          commit_message: "Updated from CI"
          commit_user_name: Naviteq Automation
          commit_user_email: naviteq-automation@naviteq.io
