---

name: Helm Release OCI TEST
on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  case_core_action_success:
    name: Case - OCI core action succeeds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run OCI core action
        id: core
        uses: ./.github/actions/helm-release-oci
        with:
          chart_path: fixtures/helm-release-oci/helm-chart
          oci_registry: ghcr.io
          oci_repo: naviteq/github-actions-tests
          push_chart: "false"
          bump_version_in_git: "false"
          lint_enabled: "true"
          chart_version: "" # test empty

  case_github_wrapper_success:
    name: Case - GitHub wrapper succeeds
    uses: ./.github/workflows/helm-release-github.yaml
    with:
      chart_path: fixtures/helm-release-oci/helm-chart
      ghcr_repo: ${{ github.repository }}
      push_chart: false
      bump_version_in_git: false
      lint_enabled: true
      chart_version: "1.0.0-override" # test override

  case_ecr_wrapper_success:
    name: Case - ECR wrapper succeeds
    uses: ./.github/workflows/helm-release-ecr.yaml
    with:
      chart_path: fixtures/helm-release-oci/helm-chart
      ecr_registry: 000000000000.dkr.ecr.eu-west-1.amazonaws.com
      ecr_repo: test/charts
      push_chart: false
      bump_version_in_git: false
      lint_enabled: true

  case_gar_wrapper_success:
    name: Case - GAR wrapper succeeds
    uses: ./.github/workflows/helm-release-gar.yaml
    with:
      chart_path: fixtures/helm-release-oci/helm-chart
      gar_registry: europe-west1-docker.pkg.dev
      gar_repo: test-project/test-repo
      push_chart: false
      bump_version_in_git: false
      lint_enabled: true
