name: Checkov / Checkov TEST

on:
  workflow_call:
  workflow_dispatch:

jobs:
  case_soft_fail_success:
    strategy:
      matrix:
        framework: [terraform, kubernetes, helm]
    name: Case - soft fail succeeds
    uses: ./.github/workflows/security-checkov.yaml
    with:
      directory: fixtures/security-checkov
      framework: ${{ matrix.framework }}
      soft_fail: true
