name: Security / Trivy TEST

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  case_image_scan_success:
    name: Case - image scan succeeds
    uses: ./.github/workflows/security-trivy.yml
    with:
      RUNNER: ubuntu-latest
      scan_type: image
      image_ref: cgr.dev/chainguard/nginx:latest
