---

name: Terraform modules testing
on:
  workflow_call:
    inputs:
      AWS_REGION:
        type: string
      TEST_EXTRA_COMMANDS:
        type: string
        required: false
        default: ""
      PRE_PIP_COMMANDS:
        type: string
        required: false
        default: ""
      EXTRA_ENV_VARS:
        type: string
        required: false
        default: ""
    secrets:
      AWS_IAM_ROLE:
        required: true
      RUNNERS_PAT_TOKEN:
        required: false
      NAVITEQ_TF_TOKEN:
        required: false
jobs:
  prepare:
    name: Preparation
    runs-on: ubuntu-latest
    outputs:
      runners: ${{ steps.vars.outputs.github_runners }}
    steps:
      - uses: actions/checkout@v3
      - name: Outputs preparation
        id: vars
        env:
          GH_TOKEN: ${{ secrets.RUNNERS_PAT_TOKEN }}
        run: |
          github_runners='ubuntu-latest'
          runners=$(gh api repos/${{ github.repository }}/actions/runners | jq .total_count || echo 0) && echo $runners
          org_runners=$(gh api /orgs/naviteq/actions/runners | jq .total_count || echo 0) && echo $org_runners
          ([[ "$runners" -gt 0 ]] || [[ "$org_runners" -gt 0 ]]) && github_runners="self-hosted"
          echo "github_runners=${github_runners}" >> $GITHUB_OUTPUT
  format:
    name: Format check
    runs-on: ubuntu-22.04
    needs: [prepare]
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6
          cli_config_credentials_hostname: 'terraform.naviteq.io'
          cli_config_credentials_token: ${{ secrets.NAVITEQ_TF_TOKEN }}
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Python format
        uses: psf/black@stable
        with:
          version: 22.6.0
      - name: Terraform Format
        run: terraform fmt --check --recursive --diff
  tflint:
    name: TFLint
    runs-on: ${{ needs.prepare.outputs.runners }}
    needs: [prepare]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('.tflint.hcl') }}
      - uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: v0.47.0
      - name: Run TFLint
        run: |
          tflint --init
          tflint -f compact
  security:
    name: Security
    runs-on: ${{ needs.prepare.outputs.runners }}
    needs: [prepare]
    env:
      CHECKOV_ENABLE_MODULES_FOREACH_HANDLING: "False"
      CHECKOV_NEW_TF_PARSER: "0"
    steps:
      - uses: actions/checkout@v3
      - name: TFSec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          additional_args: --config-file=./.tfsec.yml
          version: v1.28.1
      - name: Run Checkov action
        uses: bridgecrewio/checkov-action@v12.2455.0
        with:
          quiet: true
  test:
    name: Module testing (PyTest)
    concurrency: tf-test-${{ github.ref }}
    runs-on: ${{ needs.prepare.outputs.runners }}
    needs:
      - prepare
      - format
      - tflint
      - security
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6
          terraform_wrapper: false
      - uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv
        with:
          requirement_files: tests/requirements.txt
      - uses: syphar/restore-pip-download-cache@v1
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'
      - run: eval ${PRE_PIP_COMMANDS}
        if: ${{ inputs.PRE_PIP_COMMANDS }} != ""
        env:
          PRE_PIP_COMMANDS: ${{ inputs.PRE_PIP_COMMANDS }}
      - run: pip install -r tests/requirements.txt
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          role-session-name: github-${{ github.repository_id }}-${{ github.triggering_actor }}
          aws-region: ${{ inputs.AWS_REGION }}
      - name: Tests run
        run: |
          if [ -n "${TEST_EXTRA_COMMANDS}" ]; then eval ${TEST_EXTRA_COMMANDS}; fi
          if [ -n "${EXTRA_ENV_VARS}" ]; then export ${EXTRA_ENV_VARS}; fi
          python -m pytest -vvv
        env:
          TEST_EXTRA_COMMANDS: ${{ inputs.TEST_EXTRA_COMMANDS }}
          EXTRA_ENV_VARS: ${{ inputs.EXTRA_ENV_VARS }}
          TF_TOKEN_terraform_naviteq_io:  ${{ secrets.NAVITEQ_TF_TOKEN }}
