---

name: Terraform modules release
on:
  workflow_call:
    inputs:
      AWS_REGION:
        type: string
      S3_BUCKET:
        type: string
      NAMESPACE:
        type: string
      NAME:
        type: string
      PROVIDER:
        type: string
    secrets:
      AWS_IAM_ROLE:
        required: true
jobs:
  release:
    name: Module registry release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
      - uses: unfor19/install-aws-cli-action@v1.0.3
      - name: Create archive
        run: tar ${exclude_args} -cvzf module.tgz ./*
        env:
          exclude_args: --exclude='./github' --exclude="./examples" --exclude="./tests" --exclude='./*.y*'
      - uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          role-session-name: github-${{ github.repository_id }}-${{ github.triggering_actor }}
          aws-region: ${{ inputs.AWS_REGION }}
      - name: Push module to the s3
        run: aws s3 cp ./module.tgz s3://$BUCKET/${OBJECT_PATH}/${OBJECT}
        env:
          BUCKET: ${{ inputs.S3_BUCKET }}
          OBJECT_PATH: modules/${{ inputs.NAMESPACE }}/${{ inputs.NAME }}/${{ inputs.PROVIDER }}/${{ env.VERSION }}
          OBJECT: ${{ inputs.NAMESPACE }}-${{ inputs.NAME }}-${{ inputs.PROVIDER }}-${{ env.VERSION }}.tar.gz
