name: Security / Trivy Runner

on:
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  trivy:
    uses: ./.github/workflows/security-trivy.yml
    with:
      RUNNER: ubuntu-latest
      scan_type: image
      image_ref: cgr.dev/chainguard/nginx:latest