name: IaC Security Scan

on:
  workflow_dispatch:

jobs:
  checkov:
    uses: ./.github/workflows/security-checkov.yaml
    with:
      directory: fixtures/security-checkov
      framework: terraform,kubernetes,helm
      soft_fail: false
