name: IaC Security Scan

on:
  workflow_dispatch:

jobs:
  checkov:
    uses: ./.github/workflows/security-checkov.yaml
    with:
      directory: .github/testdata/security-checkov
      framework: terraform,kubernetes,helm
      soft_fail: false
